// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShortenerCache is an autogenerated mock type for the ShortenerCache type
type ShortenerCache struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, short, original
func (_m *ShortenerCache) Add(ctx context.Context, short string, original string) error {
	ret := _m.Called(ctx, short, original)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, short, original)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOriginal provides a mock function with given fields: ctx, short
func (_m *ShortenerCache) GetOriginal(ctx context.Context, short string) (string, error) {
	ret := _m.Called(ctx, short)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, short)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, short)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, short)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: ctx, short
func (_m *ShortenerCache) Remove(ctx context.Context, short string) error {
	ret := _m.Called(ctx, short)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, short)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewShortenerCache creates a new instance of ShortenerCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenerCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenerCache {
	mock := &ShortenerCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
