clickhouse_url: "clickhouse://localhost:9000/"
kafka_brokers:
  - "localhost:9092"
  - "localhost:9093"
  - "localhost:9094"
kafka_consumer_group_id: "shortener-consumer-group"
kafka_topics:
  - "shortener-events"